### ISSUE TITLE
Criar landing page da comunidade

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/backend-br.github.io#1]

**Comment by diegocoxta** [comment]
Pode contar comigo no frontend :)
Só precisamos subornar um designer.

**Comment by reginaldojunior** [comment]
Verdade! Vou falar com uns amigos meus. Qualquer coisa usamos algum modelo, não precisa se nada muito complexo agora no começo.

**Comment by diegocoxta** [comment]
Mas antes de pensar na landing precisamos decidir como será o logo oficial. backend-br/forum#3

**Comment by reginaldojunior** [comment]
Sim! Precisamos de um logo. Pensei em algo parecido com o atual.

**Comment by vitorleonel** [comment]
Já tiveram alguma ideia?

Podem contar comigo para ajudar no front-end e/ou back-end :)

**Comment by reginaldojunior** [comment]
Estamos ainda pendentes de desenvolver um logo, mas estou pensando em algo simples no começo. Como essa (https://openschoolbr.github.io/) e vamos modificando com o tempo, acrescentando mais features etc... Quem tiver ideias coloca aqui que já definimos e começamos a codificar.

**Comment by thiagoluiznunes** [comment]
Pode contar comigo também galera, relacionado a logo eu sou leigo, porém, back e front eu posso contribuir.

**Comment by reginaldojunior** [comment]
Esse final de semana vou começar algo...

**Comment by thiagoluiznunes** [comment]
Eu estarei livre a partir de segunda porque tenho uma prova no dia.

**Comment by reginaldojunior** [comment]
Comecei algumas coisas já, mas ainda nada fixo. A ideia é um site em vue.js consumindo as API's do GitHub mostrando as issues dos repositórios vagas, forum etc...

**Comment by diegocoxta** [comment]
Sou dev React mas vamos de Vue!
Sugestão de página legal que podemos seguir na landing https://opensource.globo.com

@reginaldojunior  O que você acha da página da Globo?

**Comment by reginaldojunior** [comment]
Gostei :+1:

**Comment by diegocoxta** [comment]
Acho que vamos precisar de um canal no Slack, essas conversas por aqui vão ficar extensas.

**Comment by reginaldojunior** [comment]
https://backend-br.slack.com/messages

Preciso dos emails para enviar os invites, e fazer aquele botão para enviar o e-mail automático, sabe fazer?

Procurei algumas coisas e não achei.

**Comment by diegocosta** [comment]
diego@diegocosta.com.br :)

Sobre automatização de convites, só conheço esse serviço: https://github.com/outsideris/slack-invite-automation

**Comment by reginaldojunior** [comment]
https://join.slack.com/t/backend-br/shared_invite/MjI2MTM2MjMwNjI4LTE1MDI2Nzg0NjYtNDFjNjc4MTg2Mg

**Comment by reginaldojunior** [comment]
O @diegocosta fez este icone/logo para gente...

![backendbr-logo](https://user-images.githubusercontent.com/7466894/29522940-8a2d36f0-8661-11e7-8baa-5093fb5f7c4d.png)

O que acham?

**Comment by thiagoluiznunes** [comment]
Foi show, so não sei a bandeira do brasil atras ficou legal.

**Comment by thiagoluiznunes** [comment]
Mas ta muito bom mesmo, excelente trabalho.

**Comment by nicholasess** [comment]
Esse é o meu esboço em relação ao site, aceito feedbacks!
![landing page](https://user-images.githubusercontent.com/3238901/29681702-ee3b54f4-88de-11e7-8a53-e859f0e5c70e.png)

**Comment by reginaldojunior** [comment]
Boa GOSTEI! 

Invés do fundo verde podemos colocar uma imagem, e adicionar mais algumas coisas dps.

Mas é isso mesmo, ficou bem louco... Parabéns ai!! 

❤️

**Comment by reginaldojunior** [comment]
@nicholasess você  está no nosso slack? Acessa lá dps, estamos conversando por lá algumas coisas também...

**Comment by reginaldojunior** [comment]
PS: Gostei dos stars "666" 💀

**Comment by gspaiva** [comment]
@nicholasess Ficou mt bom cara!

**Comment by diegocoxta** [comment]
@nicholasess Gostei, me lembrou o http://free-time.github.io

**Comment by thiagoluiznunes** [comment]
Ta show.

**Comment by nicholasess** [comment]
@reginaldojunior qual é a url do slack?

**Comment by reginaldojunior** [comment]
@nicholasess https://join.slack.com/t/backend-br/shared_invite/MjI2MTM2MjMwNjI4LTE1MDI2Nzg0NjYtNDFjNjc4MTg2Mg

**Comment by nicholasess** [comment]
@reginaldojunior a ideia é essa mesmo, fiz no sketch, então só preciso enviar um PR com o arquivo no repositório e qualquer necessidade, basta editar.

**Comment by thiamsantos** [comment]
Vocês não acham que é muita coisa incluir React + Bootstrap + JQuery, só para fazer uma landing page? Não seria melhor usar uma abordagem mais simplificada talvez usando vanilla js e nenhum framework css?

**Comment by diegocoxta** [comment]
@thiamsantos É muita coisa sim, estou planejando tirar o Bootstrap+JQuery, só portamos o que já tinha pro React. A ideia é a web app crescer com o surgimento de novos projetos 👍

**Comment by vitorleonel** [comment]
@reginaldojunior seria valido a ideia de usar o vuejs com o bulma.io?

**Comment by reginaldojunior** [comment]
@thiamsantos a ideia é crescer mesmo não ser só uma landing-page. 

Implementar novas features no webapp igual o @diegocosta falou. Estou pensando em várias coisas aqui que podemos fazer que vamos poder contribuir para a comunidade através de um webapp.

@vitorleonel acredito que não vale a pena mudar agora mais para o vuejs já que começamos a trabalhar com o React.

**Comment by diegocoxta** [comment]
Acho que fechamos essa issue né?

**Comment by reginaldojunior** [comment]
sim :smile: :heart:
