### ISSUE TITLE
Precisamos mesmo do Bootstrap?

### ISSUE THREAD

**Issue by diegocoxta** [backend-br/backend-br.github.io#10]
Precisamos mesmo do Bootstrap? Não vejo utilidade do framework nesse projeto, estamos carregando a build completa apenas pelo sistema de grids.

**Comment by khaueviana** [comment]
Acho que não hehe

Segundo meu conhecimento básico de front, só usar um css pro grid e fim! hehe

**Comment by reginaldojunior** [comment]
Eu também acho que não precisa 👍
