### ISSUE TITLE
Criação README com padrões de divulgação das Vagas

### ISSUE THREAD

**Issue by khaueviana** [backend-br/backend-br.github.io#11]
Farei!

**Comment by nicholasess** [comment]
Criei há 26 dias atrás esse manifesto, acredito que seja um ponto de partida e se puderem usar essas diretrizes, ficaria grato.
https://github.com/nicholasess/manifesto-vagas-dev

**Comment by khaueviana** [comment]
Opa @nicholasess faz um fork do projeto e cria uma PR com essa sugestão. Pode ser?

Dá uma olhada nesse também: https://github.com/frontendbr/vagas

**Comment by nicholasess** [comment]
@khaueviana dei uma sugestão quanto a atualização do README para vagas, não poderei fazer isso...
