### ISSUE TITLE
Link do site para o Slack não está funcionando

### ISSUE THREAD

**Issue by ghost** [backend-br/backend-br.github.io#21]
Boa noite!

   O link do site para o slack não está funcionando. 
   Ao abrir a página a mensagem "This invite link is no longer active. Please check with the person who shared it with you to see if there's a new link available." é exibida.

**Comment by gustavocstl** [comment]
Opa, boa noite!

Tenta usar esse:
https://join.slack.com/t/backend-br/shared_invite/enQtMjQyOTM1MjQ5OTcyLTA1NTJiODM5YTA2YzYyZDUyMGRiNTc1NjAwODNhYTQ3OTlkYjE2ZDllMTc2MzlmNzFmOTI4Mzc2NWFhNzE2OTg

**Comment by ghost** [comment]
Bom dia!

Testei o link novo e deu certo. 

Muito obrigado!
