### ISSUE TITLE
Site fora do AR. 

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/backend-br.github.io#22]
Site carrega, mas tudo some e da uns erros no console.

**Comment by reginaldojunior** [comment]
@diegocosta sabe o que pode ser?

**Comment by diegocoxta** [comment]
Vou investigar o problema :)

**Comment by reginaldojunior** [comment]
Obrigado, precisar de algo me avisa.

**Comment by reginaldojunior** [comment]
Vocês são uns amores <3
