### ISSUE TITLE
Transformar HTML e CSS do master para React

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/backend-br.github.io#3]
Transformar o HTML e o CSS disponível no master para React.

**Comment by diegocoxta** [comment]
Já estou trabalhando nisso, vou dar o start com o create-react-app, fazer as configurações básicas para servir uma gh-page e tentar transformar os elementos atuais em componentes stateless.

Outra coisa, estou adotando o padrão de commits em português, se o intuito é ser uma fonte de informação brasileira, temos que ser inclusivos até com o idioma.

**Comment by reginaldojunior** [comment]
Boa! @diegocosta ... Ficou show, vamos deixar em português como padrão então... Vou fechar a tarefa 😄
