### ISSUE TITLE
[Proposta] Reescrever o site sem FW e melhorar o SEO/etc

### ISSUE THREAD

**Issue by onhernandes** [backend-br/backend-br.github.io#32]
O site hoje é feito em React e isso atrapalha no SEO e localização pelos motores de busca e etc, sem contar que nem todos conhecem React para dar manutenção no projeto.

Estava pensando em refazer o site com HTML/CSS puro mesmo, talvez usando o [hexo](hexo.io), que é um gerador estático.

A ideia é só mudar pra HTML/CSS puro, sem mudar o layout. Permanecerá exatamente o mesmo.

O que acham?

cc @diegocosta @gucastiliao

**Comment by diegocoxta** [comment]
Eu acho que se for pra mexer nele é melhor fazer algo mais grandioso. 
Novo layout, novo branding, nova abordagem.

**Comment by onhernandes** [comment]
@diegocosta eu sinceramente sou péssimo pra desenhar um novo layout, mas gosto de codar hehe. Se você e/ou o @gucastiliao desenharem algo, eu topo codar.

**Comment by reginaldojunior** [comment]
Sim, se for para mexer tem que ser algo foda mesmo. Para chamar atenção de vdd, com todos mostrando todos os tópicos e frente que estamos procurando mudar. 

Discernir conhecimento, mais conteudo de tecnologia em português, diversificação na área de tecnologia, tecnologia e startups alcançando as periferias em conhecimento e em  empreendedorismo.

**Comment by diegocoxta** [comment]
@onhernandes @reginaldojunior  Será que n conseguem um designer voluntário? :p

**Comment by onhernandes** [comment]
@diegocosta vou publicar no Twitter do BackEndBrasil e ver se alguém pode ajudar
