### ISSUE TITLE
filtro das vagas não é respeitado ao acionar botão "Carregar mais"

### ISSUE THREAD

**Issue by jojoyuji** [backend-br/backend-br.github.io#42]
Ao clicar no botão "carregar mais" da seção Vagas, tendo filtrado o estado, carrega dados sem respeitar o filtro 😅

**Comment by grippado** [comment]
Estava vendo o código que foi usado pra aplicar o filtro das vagas, e ele ta fazendo uma comparação simples de texto no `location` de cada vaga/issue, para o `value` de cada option do select, e isso, por não ter um padrão, faz com que o filtro não funcione corretamente, pensei em fazer uma biblioteca simples com um de->para de cada cidade para o respectivo estado, mas isso torna, a longo prazo, o codigo meio inviável, e pesado demais, pois em uma possibilidade distante, de ter todos os municipios do BR cadastrado, ficaria algo completamente insano de grande!
O que pensei que poderia ser feito, para que isso fosse resolvido, e com alteração mínima de código, é uma padronização do location quando a vaga é cadastrada, contendo sempre a sigla do estado em questão da vaga, e os `values` dos options de estados, serem trocados do nome do estado por extenso, para a sigla, fazendo com que a acuracidade do filtro seja 100%!!
Fiz um teste simples aqui: 
![image](https://user-images.githubusercontent.com/550632/50640813-23db8c00-0f4d-11e9-817c-5703cf941166.png)
troquei `Minas Gerais` pra `MG` no option do respectivo estado, e o select passou a funcionar para todos os locations que contem o texto `MG`, a meu ver, é a forma mais simples, e que evita ter de refatorar e/ou reescrever código para ter de ficar "testando" cada cidade, e assim como citei acima, resolvendo o problema do `match value` do filtro que ta bem escrito, mas não tem congruência de dados com o valor que ele procura por não ter esse padrão dos estados em cada vaga/issue!
=)

**Comment by Pliavi** [comment]
@grippado isso resolve um problema que não é bem o da issue, mas boa (até facilita).

O caso deles lá é que o filtro não é passado quando uma requisição de novas vagas é dada (quando clica no "carregar vagas"), acabei de abrir então não tenho ideia ainda, mas deve ser só chamar a ação do filtro após ela.

E encontrei outra, quando clica em "carregar vagas" sem filtro, somem todas as vagas (Quando anteriormente você selecionou um região sem vagas).

--edit
Oh well, acho que é mais treta do que parece... Dá pra por filtro de nome na API do Github? Porque ele tá puxando a próxima pagina de issues, **com qualquer estado**, aqui tá vindo 30, se filtrar esses 30, cada página vai vir com quantidades diferentes de vagas e pode ser até que não venha nenhuma!

Fora que quando você troca de estado no select ele não reseta a página, se você coloca RJ, carrega mais, ele puxa página 2, vai pra SP e manda carregar mais ele vai pra página 3 e não 2 novamente por ser outro estado.

**Comment by grippado** [comment]
@Pliavi, na verdade, a issue principal, lá no backend-be, o problema relatado é sobre o não carregamento das vagas quando selecionado os estados mesmo!
e eu foquei em procurar uma solução pra ela em específico, pra parte do carregamento quando clicar em carregar mais, tanto a API do gh estourando limite, quanto uma classe hidden que não é removida, são os problemas!
somente removendo-a do CSS, isso para de acontecer!
e solucionando a parte do filtro como eu escrevi direto na issue, também é solucionado a parte do carregar mais utilizando o filtro! :)

**Comment by onhernandes** [comment]
A solução do @grippado vai ajudar bastante, e pode ser aplicada junto com essa correção =)

O filtro é aplicado no HTML, direto no navegador, porque a API Github não suporta os filtros que temos no site. Tá no roadmap, criar uma API nossa, com uma filtragem nativa, assim não precisa ser feita no navegador - não como é feito hoje.

Como o filtro todo é aplicado no HTML, quando tu recarrega mais `issues`, o filtro não é re-aplicado - eu lembro de ter tentado fazer isso mas não consegui, e tava na correria.

Como disse lá na https://github.com/frontendbr/open-source/issues/76, é aberto a refatoração porque acredito que precise reorganizar bastante coisa.

**Comment by onhernandes** [comment]
A correção paliativa já foi feita, em breve vamos melhorar definitivamente com uma API suportando sinônimos e etc. 

Obrigado a todos.

Fechando issue
