### ISSUE TITLE
backendbrasil.com.br 404: NOT_FOUND

### ISSUE THREAD

**Issue by AlexOliveiraaDev** [backend-br/backend-br.github.io#50]
Site fora do ar.

404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: gru1::6fkxv-1715089653793-23cd8ac57a9d
![imagem_2024-05-07_104817868](https://github.com/backend-br/backend-br.github.io/assets/157441640/d84e041f-d5c7-48ee-8f45-808c8029968b)

**Comment by gustavofreze** [comment]
Não temos mais o DNS
