### ISSUE TITLE
Criar conteúdo sobre

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/backend-br.github.io#6]
Criar conteúdo para pagina inicial e para o readme falando sobre a comunidade.

**Comment by reginaldojunior** [comment]
@khaueviana Consegue pegar essa?

**Comment by khaueviana** [comment]
@reginaldojunior sim!!!

**Comment by khaueviana** [comment]
@reginaldojunior e @diegocosta terá esse espaço no site mesmo? posso criar o conteúdo?

**Comment by diegocoxta** [comment]
@khaueviana Caso queiram, posso colocar no site :p

**Comment by khaueviana** [comment]
@diegocosta acho que é legal hehe @reginaldojunior ?

**Comment by reginaldojunior** [comment]
Eu acho que devemos colocar sim, para ficar mais informativo.

**Comment by khaueviana** [comment]
Blz :)
